name: Periodic Health Check

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  periodic_health_check:
    runs-on: ubuntu-24.04
    steps:
      - name: Check the live URL health
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" https://full-stack-open-pokedex-6ath.onrender.com/)
          if [ "$response" != "200" ]; then
            echo "Health check failed with status $response"
            exit 1
          fi
          echo "Health check passed with status 200!"