name: Periodic Health Check

on:
  schedule:
    # This "cron" string tells GitHub to run this job every day at midnight UTC
    - cron: '0 0 * * *'
  # This lets us manually trigger it from the GitHub website whenever we want to test it
  workflow_dispatch:

jobs:
  periodic_health_check:
    runs-on: ubuntu-24.04
    steps:
      - name: Check the live URL health
        uses: jasonatallah/request-action@v2
        with:
          url: 'https://full-stack-open-pokedex-6ath.onrender.com/health'
          method: 'GET'
          # We expect a successful 200 OK HTTP response status
          expected_statuses: '200'